pipeline {
    agent only

    stage{

        stage('Compile only'){

        steps {
            withMaven(maven : 'maven_3_5_0'){
                sh 'mvn clean compile'
                }
            }

        }

        stage('Testing only'){
            steps{

                withMaven(maven : 'maven_3_5_0'){
                    sh 'mvn test'
                }

            }
        }

       stage ('Deployment Stage') {
                    steps {
                        withMaven(maven : 'maven_3_5_0') {
                            sh 'mvn deploy'
                        }
                    }
                }

}

    }




}